menambahkan file baru
ika776/belajar-git pull request #1
Opened 2021-07-11 04:50 UTC by ika776

2021-07-11 07:05 UTC, bhagas commented
Di isi ya filenya, terserah mau di isi apa, terus add commit push lg

2021-07-11 07:15 UTC, ika776 commented
sudah ditambahkan beberapa huruf dalam file coba.txt

2021-07-11 07:46 UTC, bhagas requested changes

2021-07-11 07:46 UTC, bhagas commented on coba.txt
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
Oke sekarang coba tambahkan nama dan alamat dibawahnya ya

2021-07-11 13:54 UTC, ika776 commented
sudah ditambahin nama dan alamat

2021-07-11 15:23 UTC, bhagas commented on coba.txt
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
oke sekarang boleh di merge

2021-07-11 15:23 UTC, bhagas approved these changes

2021-07-11 15:24 UTC, bhagas commented
oke sudah boleh di merge

2021-07-12 01:46 UTC, merged

2021-07-12 01:50 UTC, ika776 commented
sudah merged